on:
  push:
    branches:
      - main
    paths:
      - 'lambda1/**'
      - 'lambda2/**'
jobs:
  changes:
    name: Detect Changes in folder
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - name: Detect Changes
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          lambda1:
            - 'lambda1/**'
          lambda2:
            - 'lambda2/**'
   activate-workflow:
    needs: changes
    if: ${{ needs.changes.outputs.names != '[]' }}
    name:  Deploying lambda(s) funtion(s) ${{ (matrix.workflow ) }}  
    strategy:
      matrix:
        workflow: ${{ fromJSON(needs.changes.outputs.names) }}
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      stage: dev
      resource: ${{ (matrix.workflow ) }} 
