on:
  push:
    branches:
      - main
    paths:
      - 'lambda1/**'
      - 'lambda2/**'
jobs:
  changes:
    name: Detect Changes in folder
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - name: Detect Changes
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          lambda1:
            - 'lambda1/**'
          lambda2:
            - 'lambda2/**'
  activate-workflow:
    needs: changes
    if: ${{ needs.changes.outputs.names != '[]' }}
    name:  ${{matrix.name}} - ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
         name: ${{ fromJSON(needs.changes.outputs.names) }}
         environment: [ test,prod]
    
    steps:
      - uses: ./.github/workflows/reusable-workflow.yml
        with:
          stage: dev
          resource: ${{ matrix.name }} 