on:
  push:
    branches:
      - main
    paths:
      - 'lambda1/**'
      - 'lambda2/**'
jobs:
  changes:
    name: Detect Changes in folder
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - name: Detect Changes
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          lambda1:
            - 'lambda1/**'
          lambda2:
            - 'lambda2/**'
  print-output:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.names != '[]' }}
    steps:
     - name: Print output selected
       run: echo values selected- ${{ fromJSON(needs.changes.outputs.names) }} 

  activate-workflow:
    needs: changes
    if: ${{ needs.changes.outputs.names != '[]' }}
    name:  ${{matrix.name}} - ${{ matrix.environment }}
    strategy:
      matrix:
        #workflow: ${{ (needs.changes.outputs.names) }}
        workflow: ["lambda1", "lambda2"]
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      stage: dev
      resource: ${{ fromJSON(matrix.workflow ) }} 
