name: Continuous integration 

on:
  pull_request:
    types: 
      - closed
    branches:
      - develop
  push:
    branches:
      - "feature*"
    
    paths:
      - 'addresses/**'
      - 'admin-notification/**'
      - 'annual-price/**'
      - 'appliances/**'
      - 'auth/**'
      - 'automatic-ftp/**'
      - 'automatic-target-load/**'
      - 'card-token/**'
      - 'check-in/**'
      - 'consumption/**'
      - 'contracts/**'
      - 'data/**'
      - 'dualization-campaign/**'
      - 'email-sent-archive/**'
      - 'erroneous-payment-deletion/**'
      - 'export-power-consultancy/**'
      - 'facilita/**'
      - 'fidelisation-catalog-update/**'
      - 'gateway-orders/**'
      - 'generic-event-export/**'
      - 'help/**'
      - 'hiring/**'
      - 'inquires/**'
      - 'invoice-notification/**'
      - 'invoices/**'
      - 'login-reporting/**'
      - 'mailing-function/**'
      - 'managements/**'
      - 'no-consent-reporting/**'
      - 'payment/**'
      - 'points/**'
      - 'power-advisory/**'
      - 'power-change/**'
      - 'power-consultancy/**'
      - 'profile/**'
      - 'reading-contribution/**'
      - 'reprocess-unsent-mail/**'
      - 'sign-up/**'
      - 'sms-token-expiration/**'
      - 'social-bonus/**'
      - 'splitting/**'
      - 'street-load/**'
      - 'subtask-payment-check/**'
      - 'unsent-email-reporting/**'
      - 'update-offices/**'
      - 'update-payment-information/**'
      - 'update-streepmap/**'
      - 'lambda1/**'
      - 'lambda2/**'
jobs:
  activate-workflow:  
    runs-on: ubuntu-latest
    outputs:
      file_changes: ${{ steps.run-script.outputs.file_changes }}
    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
    - name: Run script file
      id: run-script
      run: |
         chmod +x ./.github/workflows/1.sh
         echo "file_changes=$(./.github/workflows/1.sh)" >> $GITHUB_OUTPUT
      shell: bash
  
  test-load:
    name: Test load 
    runs-on: ubuntu-latest
    needs: activate-workflow
    if: ${{ needs.activate-workflow.outputs.file_changes != '[]' }}
    strategy:
      matrix:
        source: ${{ fromJSON(needs.activate-workflow.outputs.file_changes) }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ (matrix.source) }} 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup jdk
        uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc
        with:
          java-version: 11
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install ${{ inputs.maven-params }} --file pom.xml   

      - name: print folder
        run: ls -la ./target/

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "./target/surefire-reports/*.xml"

  check-vulnerabilities:
    name: Check vulnerabilities 
    runs-on: ubuntu-latest
    needs: activate-workflow
    if: ${{ needs.activate-workflow.outputs.file_changes != '[]' }}
    strategy:
      matrix:
        source: ${{ fromJSON(needs.activate-workflow.outputs.file_changes) }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ (matrix.source) }} 
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        # Override language selection by uncommenting this and choosing your languages
        with:
           languages: java

      # Autobuild attempts to build any compiled languages (C/C++, C#, Go, or Java).
      # If this step fails, then you should remove it and run the build manually (see below).
      - name: Setup jdk
        uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc
        with:
          java-version: 11
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install ${{ inputs.maven-params }} --file pom.xml   

      - name: print folder
        run: ls -la ./target

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  launch-deploy:
    needs: [activate-workflow, check-vulnerabilities]
    if: ${{ needs.activate-workflow.outputs.file_changes != '[]' }}
    strategy:
      matrix:
        version: ${{ fromJSON(needs.activate-workflow.outputs.file_changes) }}
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      stage: dev
      resource: ${{ (matrix.version) }}    

      
 

