name: Continuous integration 

on:
  pull_request:
    types: 
      - closed
    branches:
      - develop
  push:
    branches:
      - "feature*"
    
    paths:
      - 'addresses/**'
      - 'admin-notification/**'
      - 'annual-price/**'
      - 'appliances/**'
      - 'auth/**'
      - 'automatic-ftp/**'
      - 'automatic-target-load/**'
      - 'card-token/**'
      - 'check-in/**'
      - 'consumption/**'
      - 'contracts/**'
      - 'data/**'
      - 'dualization-campaign/**'
      - 'email-sent-archive/**'
      - 'erroneous-payment-deletion/**'
      - 'export-power-consultancy/**'
      - 'facilita/**'
      - 'fidelisation-catalog-update/**'
      - 'gateway-orders/**'
      - 'generic-event-export/**'
      - 'help/**'
      - 'hiring/**'
      - 'inquires/**'
      - 'invoice-notification/**'
      - 'invoices/**'
      - 'login-reporting/**'
      - 'mailing-function/**'
      - 'managements/**'
      - 'model/**'
      - 'no-consent-reporting/**'
      - 'payment/**'
      - 'points/**'
      - 'power-advisory/**'
      - 'power-change/**'
      - 'power-consultancy/**'
      - 'profile/**'
      - 'reading-contribution/**'
      - 'reprocess-unsent-mail/**'
      - 'sign-up/**'
      - 'sms-token-expiration/**'
      - 'social-bonus/**'
      - 'splitting/**'
      - 'street-load/**'
      - 'subtask-payment-check/**'
      - 'unsent-email-reporting/**'
      - 'update-offices/**'
      - 'update-payment-information/**'
      - 'update-streepmap/**'
      - 'lambda1/**'
      - 'lambda2/**'
jobs:
  activate-workflow:  
    runs-on: ubuntu-latest
    outputs:
      file_changes: ${{ steps.run-script.outputs.file_changes }}
    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
    - name: Run script file
      id: run-script
      run: |
         chmod +x ./.github/workflows/1.sh
         echo "file_changes=$(./.github/workflows/1.sh)" >> $GITHUB_OUTPUT
      shell: bash
  
  
  security-scan:
    name: Deploy to environment ${{ github.ref_name }} && ${{ github.ref_name != 'develop' }}
    needs: activate-workflow
    if: ${{ needs.activate-workflow.outputs.file_changes != '[]' &&  github.ref_name != 'develop'}}
    strategy:
      matrix:
        version: ${{ fromJSON(needs.activate-workflow.outputs.file_changes) }}
    uses: ./.github/workflows/security-workflow.yml
    with:
      stage: ${{ github.ref_name }}
      resource: ${{ (matrix.version) }}    

  application-deploy:
    name: Deploy to environment ${{ github.ref_name }} && ${{ github.ref_name == 'develop' }} 
    needs: activate-workflow
    if: ${{ needs.activate-workflow.outputs.file_changes != '[]' && github.ref_name == 'develop'}}
    strategy:
      matrix:
        version: ${{ fromJSON(needs.activate-workflow.outputs.file_changes) }}
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      stage: develop
      resource: ${{ (matrix.version) }}     
 

