on:
  pull_request:
    types: 
      - closed
    branches:
      - develop
  push:
    branches:
      - "feature*"
    
    paths:
      - 'addresses/**'
      - 'admin-notification/**'
      - 'annual-price/**'
      - 'appliances/**'
      - 'auth/**'
      - 'automatic-ftp/**'
      - 'automatic-target-load/**'
      - 'card-token/**'
      - 'check-in/**'
      - 'consumption/**'
      - 'contracts/**'
      - 'data/**'
      - 'dualization-campaign/**'
      - 'email-sent-archive/**'
      - 'erroneous-payment-deletion/**'
      - 'export-power-consultancy/**'
      - 'facilita/**'
      - 'fidelisation-catalog-update/**'
      - 'gateway-orders/**'
      - 'generic-event-export/**'
      - 'help/**'
      - 'hiring/**'
      - 'inquires/**'
      - 'invoice-notification/**'
      - 'invoices/**'
      - 'login-reporting/**'
      - 'mailing-function/**'
      - 'managements/**'
      - 'no-consent-reporting/**'
      - 'payment/**'
      - 'points/**'
      - 'power-advisory/**'
      - 'power-change/**'
      - 'power-consultancy/**'
      - 'profile/**'
      - 'reading-contribution/**'
      - 'reprocess-unsent-mail/**'
      - 'sign-up/**'
      - 'sms-token-expiration/**'
      - 'social-bonus/**'
      - 'splitting/**'
      - 'street-load/**'
      - 'subtask-payment-check/**'
      - 'unsent-email-reporting/**'
      - 'update-offices/**'
      - 'update-payment-information/**'
      - 'update-streepmap/**'
      - 'lambda1/**'
      - 'lambda2/**'
jobs:
  
  activate-workflow:  
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.run-script.outputs.matrix.files }}
    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
    - name: Run script file
      id: run-script
      run: |
         chmod +x ./1.sh
         echo ./1.sh
      shell: bash
      