name: Create release

on:
  release:
    types: 
      - open
   
jobs:
  activate-workflow:  
    runs-on: ubuntu-latest
    outputs:
      file_changes: ${{ steps.run-script.outputs.file_changes }}
    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
    - name: Run script file
      id: run-script
      run: |
         chmod +x ./.github/workflows/1.sh
         echo "file_changes=$(./.github/workflows/1.sh)" >> $GITHUB_OUTPUT
      shell: bash
  
 
