name: Dispatcher workflow suite

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
      resource:  
        required: false
        type: string
      java-version:
        required: false
        type: string
        default: '11'
      # allowing calling workflows to pass in maven parameter(s) such as '-Dmaven.test.skip' for certain apps, default to blank, not to skip test
      maven-params:
        required: false
        type: string
        default: ''  

jobs:
   deploy-lambda-project:
    name: Deploy to ${{ inputs.stage }} the lambda function ${{ inputs.resource }}
    if: ${{ github.ref_name == 'develop' }} 
    runs-on: ubuntu-latest
    steps:
     - run: echo Build lambda image 
     - name: Set project version as environment variable
       run: echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
     
     - name: Print debug info
       run: |
          echo working_directory is ${{ inputs.resource }}
          echo project version is ${{ env.PROJECT_VERSION }}
   