name: reusable workflow

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
      resource:  
        required: true
        type: string
    #secrets:
    #  AWS_ACCESS_KEY_ID:
    #    required: true
    #  AWS_SECRET_ACCESS_KEY:
    #    required: true

jobs:
  build-and-deploy-to-dev:
    name: Deploy to ${{ inputs.stage }}
    runs-on: ubuntu-latest
    if: ${{ inputs.stage == 'dev' }}
    steps:
     - name: Deploy project from ${{ github.head_ref }} to DEV ${{ github.base_ref }} ${{ github.head_ref }}
       run: echo Deploy del proyecto en el entorno de ${{ inputs.stage }}
  build-and-deploy-to-pre:
    name: Deploy to ${{ inputs.stage }}
    runs-on: ubuntu-latest
    if: ${{ inputs.stage == 'pre' }}
    steps:
     - name: Deploy project from ${{ github.head_ref }} to DEV ${{ github.base_ref }} ${{ github.head_ref }}
       run: echo Deploy del proyecto en el entorno de ${{ inputs.stage }}
  build-and-deploy-to-pro:
    name: Deploy to ${{ inputs.stage }}
    runs-on: ubuntu-latest
    if: ${{ inputs.stage == 'pro' }}
    steps:
     - name: Deploy project from ${{ github.head_ref }} to DEV ${{ github.base_ref }} ${{ github.head_ref }}
       run: echo Deploy del proyecto en el entorno de ${{ inputs.stage }}
 