name: reusable workflow

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
      resource:  
        required: false
        type: string
    #secrets:
    #  AWS_ACCESS_KEY_ID:
    #    required: true
    #  AWS_SECRET_ACCESS_KEY:
    #    required: true

jobs:
  build-and-deploy-to-dev:
    name: Deploy to ${{ inputs.stage }} the lambda function ${{ inputs.resource }}
    runs-on: ubuntu-latest
    if: ${{ inputs.stage == 'dev' }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.resource }}
    steps:
     - uses: actions/checkout@v2
     - name: Checking the folder name
       run: |
         echo "Running for folder ${{ inputs.resource }}"
     - name: Deploy project from ${{ github.head_ref }} to DEV ${{ github.base_ref }} ${{ github.head_ref }}
       run: echo Deploy del proyecto en el entorno de ${{ inputs.stage }}
  build-and-deploy-to-pre:
    name: Deploy to ${{ inputs.stage }}
    runs-on: ubuntu-latest
    if: ${{ inputs.stage == 'pre' }}
    steps:
     - name: Deploy project from ${{ github.head_ref }} to DEV ${{ github.base_ref }} ${{ github.head_ref }}
       run: echo Deploy del proyecto en el entorno de ${{ inputs.stage }}
  build-and-deploy-to-pro:
    name: Deploy to ${{ inputs.stage }}
    runs-on: ubuntu-latest
    if: ${{ inputs.stage == 'pro' }}
    steps:
     - name: Deploy project from ${{ github.head_ref }} to DEV ${{ github.base_ref }} ${{ github.head_ref }}
       run: echo Deploy del proyecto en el entorno de ${{ inputs.stage }}
 
